#!/bin/bash
set -e

# make sure OpenHIM service is started
sleep 10

cd /etc/openhim
./load-initial-data.sh data.json

sudo -u openhim /bin/bash /etc/openhim/install_node_4.sh

chown -R openhim:openhim /usr/share/openhim-mediator-file-queue
chown -R openhim:openhim /usr/share/openhim-mediator-datim

start openhim-mediator-file-queue
start openhim-mediator-datim
