#!/bin/bash
set -e

# make sure OpenHIM service is started
sleep 10

cd /etc/openhim

# increase OpenHIM timeout to support massive initial CSD downloads
sudo sed -i -r 's/"timeout": 60000/"timeout": 3600000/' config.json

# fetch server details
. /usr/share/debconf/confmodule
db_get openhim-config/host
HOST=$RET
db_get openhim-config/port
PORT=$RET
db_get openhim-config/username
USER=$RET
db_get openhim-config/password
PASSWD=$RET

echo "Configured for OpenHIM server $HOST:$PORT using user $USER"

# inject server details
sudo sed -i -r 's/server=.*/server="'$HOST:$PORT'"/' load-initial-data.sh
sudo sed -i -r 's/username=.*/username="'$USER'"/' load-initial-data.sh
sudo sed -i -r 's/pass=.*/pass="'$PASSWD'"/' load-initial-data.sh

# inject server to mediator config
sudo sed -i -r 's/localhost:8080/'$HOST:$PORT'/' /usr/share/openhim-mediator-datim/config/config.json
sudo sed -i -r 's/localhost:8080/'$HOST:$PORT'/' /usr/share/openhim-mediator-file-queue/config/config.json

./load-initial-data.sh data.json

sudo -u openhim /bin/bash /etc/openhim/install_node_4.sh

chown -R openhim:openhim /usr/share/openhim-mediator-file-queue
chown -R openhim:openhim /usr/share/openhim-mediator-datim

# restart OpenHIM for timeout to take effect
restart openhim-core
sleep 10

stop openhim-mediator-file-queue || true
stop openhim-mediator-datim || true
start openhim-mediator-file-queue || true
start openhim-mediator-datim || true
